baseURL = "https://why.theplatypus.codes/"
languageCode = "en-us"
title = "Why The Platypus Codes"
ignoreFiles = [ ".git/.*", "scripts/.*", "public/.*", "themes/.*", "Makefile", "platypus.svg", "config.toml"]

googleAnalytics = "UA-137506633-1"

[taxonomies]
  category = "categories"
  tag = "tags"
  sources= "sources"

[params]
    avatarurl = "/platypus.svg"

# Social links
[[params.social]]
    name = "Github"
    short = "GitHub"
    weight = 1
    url = "https://github.com/whytheplatypus/"

[[params.social]]
    name = "LinkedIn"
    short = "LinkedIn"
    weight = 1
    url = "https://linkedin.com/in/dgage/"
