version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.48
    working_directory: ~/project
    steps:
      - checkout:
          path: "content"
      - run:
          name: "Create Theme Directory"
          command: "mkdir themes"
      - run:
          name: "Fetch Theme"
          working_directory: themes
          command: git clone --recurse-submodules https://github.com/whytheplatypus/hugo-monotreme monotreme
      - run:
          name: "Make public directory"
          command: git clone $PAGES_REMOTE public
      - run:
          name: "Run Hugo"
          command:  hugo -t monotreme --config content/config.toml
      - add_ssh_keys:
          fingerprints:
            - "82:16:2f:42:0c:bd:c8:61:40:51:23:ad:cc:3e:a5:ef"
      - deploy:
          name: "Github Pages"
          working_directory: public
          command: ../content/scripts/deploy.sh

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
             branches:
               only:
                 - master
